### ISSUE TITLE
[chapter12] install_fog_chef.sh script

### ISSUE THREAD

**Issue by shinobu-x** [josug-book1-materials/chapter12#1]
**chapter12**のinstall_fog_chef.sh#25行目ですが、
- echo '**chef** ALL=(ALL) ALL' > /etc/sudoers.d/fog

ではなく、
- echo '**fog** ALL=(ALL) ALL' > /etc/sudoers.d/fog

だと思います。

**Comment by n-nishida** [comment]
ご指摘ありがとうございました。修正致します。
